services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdatabasename
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
